services:
  mdbook:
    build: ./mdbook
    volumes:
      - ./mdbook:/app
    environment:
      - USER=user
    ports:
      - 9090:9090
  starlight:
    build: ./astro-starlight
    volumes:
      - ./astro-starlight:/app
    environment:
      - USER=user
    ports:
      - 8080:8080
  node:
    image: node:lts
    working_dir: /app
    volumes:
      - ./astro-starlight:/app
    ports:
      - 3000:3000
  hugo:
    image: klakegg/hugo:latest
    environment:
      - USER=user
    volumes:
      - ./hugo:/src
    command: server -D
    ports:
      - "1313:1313"